# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(382, 251)
        self.centralwidget = QtWidgets.QWidget(AddWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.degree_box = QtWidgets.QComboBox(self.centralwidget)
        self.degree_box.setObjectName("degree_box")
        self.gridLayout.addWidget(self.degree_box, 4, 1, 1, 4)
        self.kind_box = QtWidgets.QComboBox(self.centralwidget)
        self.kind_box.setObjectName("kind_box")
        self.gridLayout.addWidget(self.kind_box, 6, 1, 1, 4)
        self.desc_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.desc_edit.setObjectName("desc_edit")
        self.gridLayout.addWidget(self.desc_edit, 7, 1, 1, 4)
        self.price_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.price_edit.setObjectName("price_edit")
        self.gridLayout.addWidget(self.price_edit, 8, 1, 1, 4)
        self.volume_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.volume_edit.setObjectName("volume_edit")
        self.gridLayout.addWidget(self.volume_edit, 9, 1, 1, 4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 10, 0, 1, 5)
        AddWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddWindow)
        self.statusbar.setObjectName("statusbar")
        AddWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "AddWindow"))
        self.label_3.setText(_translate("AddWindow", "Молотый/В зернах"))
        self.label.setText(_translate("AddWindow", "Название сорта"))
        self.label_2.setText(_translate("AddWindow", "Степень обжарки"))
        self.label_5.setText(_translate("AddWindow", "Цена"))
        self.label_4.setText(_translate("AddWindow", "Описание вкуса"))
        self.label_6.setText(_translate("AddWindow", "Объем порции"))
        self.pushButton.setText(_translate("AddWindow", "Сохранить"))
